language: node_js
node_js: "8"
cache: yarn

before_install:
  - npm install -g yarn

install: yarn install

script: 
  - cp .env.example .env
  - cp localhost-cert.pem localhost-cert.pem 
  - cp localhost-privkey.pem localhost-privkey.pem 
  - yarn run test-integration-jest
  - yarn run build

services:
  - mongodb