version: '2'
services:
  web:
    container_name: api-rest
    build: .
    volumes:
      - ./:/app
    ports:
      - 3003:3003
    command:
      - './node_modules/.bin/nodemon'
    environment:
      - NODE_AMBIENTE=docker
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - ./data:/data/db